"""deleted cust_id

Revision ID: 056765a52b7c
Revises: c632ef7b197d
Create Date: 2025-06-18 20:34:00.049344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '056765a52b7c'
down_revision: Union[str, None] = 'c632ef7b197d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cust_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cust_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
