"""Added more fields to users

Revision ID: c632ef7b197d
Revises: dab830d24ee0
Create Date: 2025-06-18 20:04:52.699892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c632ef7b197d'
down_revision: Union[str, None] = 'dab830d24ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(), nullable=False))
    op.add_column('users', sa.Column('dob', sa.Date(), nullable=False))
    op.add_column('users', sa.Column('cust_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cust_id')
    op.drop_column('users', 'dob')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
