"""add deadline to tasks

Revision ID: dab830d24ee0
Revises: 2f612e8bf65c
Create Date: 2025-06-13 22:29:44.502291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dab830d24ee0'
down_revision: Union[str, None] = '2f612e8bf65c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('deadline', sa.Date(), server_default=sa.text("CURRENT_DATE + INTERVAL '10 days'"), nullable=False))
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('tasks', 'due_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'created_at')
    op.drop_column('tasks', 'deadline')
    # ### end Alembic commands ###
